# Data Exploration

In [1]:
from google.colab import files

In [ ]:
uploaded=files.upload()

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('titanic.csv')

In [ ]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [ ]:
#Inspecting Structure
#Rows and Columns

df.shape

(887, 8)

In [ ]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'PaCh', 'Fare'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=887, step=1)

In [ ]:
#Data Types of each column
df.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
PaCh          int64
Fare        float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  887 non-null    int64
 1   Pclass    887 non-null    int64
 2   Name      887 non-null    object
 3   Sex       887 non-null    object
 4   Age       887 non-null    float64
 5   SibSp     887 non-null    int64
 6   PaCh      887 non-null    int64
 7   Fare      887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB

In [ ]:
#first 5 rows by default, you can add a desired number
df.head(20)

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.7000
11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.5500
12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0000
16,0,3,Master. Eugene Rice,male,2.0,4,1,29.1250
17,1,2,Mr. Charles Eugene Williams,male,23.0,0,0,13.0000
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
19,1,3,Mrs. Fatima Masselmani,female,22.0,0,0,7.2250

In [ ]:
#Last 3 rows
df.tail(3)

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.75

In [ ]:
#Random 5 rows
df.sample(5)

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
101,0,1,Mr. Richard Frasar White,male,21.0,0,1,77.2875
67,1,3,Miss. Erna Alexandra Andersson,female,17.0,4,2,7.9250
446,1,1,Major. Arthur Godfrey Peuchen,male,52.0,0,0,30.5000
580,0,1,Mr. John Hugo Ross,male,36.0,0,0,40.1250
456,0,3,Mr. Maurice O'Connor,male,17.0,0,0,7.7500

In [ ]:
#Shows the frequency of unique values in a column
df.value_counts('Sex')

Sex
male      573
female    314
Name: count, dtype: int64

In [ ]:
#Or you can also use
df['Sex'].value_counts()

Sex
male      573
female    314
Name: count, dtype: int64

In [ ]:
#Provide descriptive statistics for numeric columns
df.describe()

         Survived      Pclass         Age       SibSp        PaCh       Fare
count  887.000000  887.000000  887.000000  887.000000  887.000000  887.00000
mean     0.385569    2.305524   29.471443    0.525366    0.383315   32.30542
std      0.487004    0.836662   14.121908    1.104669    0.807466   49.78204
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.00000
25%      0.000000    2.000000   20.250000    0.000000    0.000000    7.92500
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.45420
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.13750
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.32920

### Selecting and Indexing Coulmns

In [ ]:
#Single Columns as Series
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
882    27.0
883    19.0
884     7.0
885    26.0
886    32.0
Name: Age, Length: 887, dtype: float64

.loc selects data by label (row/column names), while .iloc selects data by integer position (0‑based index). .loc includes the end of a slice and supports boolean masks aligned to labels, whereas .iloc uses positional slicing (end-exclusive) and boolean masks by position.

In [ ]:
df.loc[:3]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000

In [ ]:
df.iloc[:3]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250

In [ ]:
#Single column as dataframe

In [ ]:
a=df["Name"]

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
b=df[['Name']]

In [ ]:
type(b)

pandas.core.frame.DataFrame

In [ ]:
#Multiple Columns as dataframe
df[['Name','Sex','Age']][:5]

                                                Name     Sex   Age
0                             Mr. Owen Harris Braund    male  22.0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0
2                              Miss. Laina Heikkinen  female  26.0
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0
4                            Mr. William Henry Allen    male  35.0

In [ ]:
df.iloc[4]

Survived                          0
Pclass                            3
Name        Mr. William Henry Allen
Sex                            male
Age                            35.0
SibSp                             0
PaCh                              0
Fare                           8.05
Name: 4, dtype: object

In [ ]:
df.loc[4]

Survived                          0
Pclass                            3
Name        Mr. William Henry Allen
Sex                            male
Age                            35.0
SibSp                             0
PaCh                              0
Fare                           8.05
Name: 4, dtype: object

In [ ]:
df[df['Age']>60]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500
169,0,1,Mr. Wyckoff Van der hoef,male,61.0,0,0,33.5000
251,0,1,Mr. William Thomas Stead,male,62.0,0,0,26.5500
273,1,1,Miss. Kornelia Theodosia Andrews,female,63.0,1,0,77.9583
278,0,3,Mr. Frank Duane,male,65.0,0,0,7.7500
324,0,3,Mr. Johan Hansen Nysveen,male,61.0,0,0,6.2375
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
453,0,1,Mr. Francis Davis Millet,male,65.0,0,0,26.5500
480,1,3,Mrs. (Hedwig) Turkula,female,63.0,0,0,9.5875
490,0,1,Mr. Ramon Artagaveytia,male,71.0,0,0,49.5042
508,0,3,Mr. James Webber,male,66.0,0,0,8.0500
535,0,3,Mr. Samuel Beard Risien,male,69.0,0,0,14.5000
542,0,1,Mr. Arthur Ernest Nicholson,male,64.0,0,0,26.0000
552,0,1,Mr. George Wright,male,62.0,0,0,26.5500
561,0,3,Miss. (Marion Ogden) Meanwell,female,62.0,0,0,8.0500
567,1,2,Mr. George Harris,male,62.0,0,0,10.5000
622,0,1,Mr. Frederick Sutton,male,61.0,0,0,32.3208
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.0,0,0,30.0000
669,0,2,Mr. Henry Michael Mitchell,male,70.0,0,0,10.5000
741,0,1,Capt. Edward Gifford Crosby,male,70.0,1,1,71.0000
825,1,1,Mrs. George Nelson (Martha Evelyn) Stone,female,62.0,0,0,80.0000
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.7750

In [ ]:
df.loc[0,'Name']

'Mr. Owen Harris Braund'

In [ ]:
df.iloc[0,2]

'Mr. Owen Harris Braund'

In [ ]:
df.loc[0:2]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250

In [ ]:
#All rows, selected columns
df.loc[:,['Name','Age']]

                                                  Name   Age
0                               Mr. Owen Harris Braund  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                                Miss. Laina Heikkinen  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
..                                                 ...   ...
882                               Rev. Juozas Montvila  27.0
883                        Miss. Margaret Edith Graham  19.0
884                     Miss. Catherine Helen Johnston   7.0
885                               Mr. Karl Howell Behr  26.0
886                                 Mr. Patrick Dooley  32.0

[887 rows x 2 columns]

In [ ]:
df[['Name','Age']]

                                                  Name   Age
0                               Mr. Owen Harris Braund  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                                Miss. Laina Heikkinen  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
..                                                 ...   ...
882                               Rev. Juozas Montvila  27.0
883                        Miss. Margaret Edith Graham  19.0
884                     Miss. Catherine Helen Johnston   7.0
885                               Mr. Karl Howell Behr  26.0
886                                 Mr. Patrick Dooley  32.0

[887 rows x 2 columns]

In [ ]:
#All rows, selected columns
df.loc[df['Age']>30,'Name'][:5]

1     Mrs. John Bradley (Florence Briggs Thayer) Cum...
3           Mrs. Jacques Heath (Lily May Peel) Futrelle
4                               Mr. William Henry Allen
6                                Mr. Timothy J McCarthy
11                              Miss. Elizabeth Bonnell
Name: Name, dtype: object

In [ ]:
#Name and age of those >=70
df.loc[df['Age']>=70,'Name']

95                Mr. George B Goldschmidt
115                    Mr. Patrick Connors
490                 Mr. Ramon Artagaveytia
627    Mr. Algernon Henry Wilson Barkworth
669             Mr. Henry Michael Mitchell
741            Capt. Edward Gifford Crosby
847                     Mr. Johan Svensson
Name: Name, dtype: object

#### Basic Operations

In [ ]:
#Simple Filtering

df[df['Fare']>250]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0000
87,1,1,Miss. Mabel Helen Fortune,female,23.0,3,2,263.0000
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
309,1,1,Miss. Emily Borie Ryerson,female,18.0,2,2,262.3750
339,1,1,Miss. Alice Elizabeth Fortune,female,24.0,3,2,263.0000
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292
738,1,1,Miss. Susan Parker Ryerson,female,21.0,2,2,262.3750

In [ ]:
#Combined Multiple Conditions
df[(df['Age']>30) & (df['Fare']>250)]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292

In [ ]:
#String Condition
df[df['Name'].str.contains("Charles")]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
17,1,2,Mr. Charles Eugene Williams,male,23.0,0,0,13.0000
27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0000
37,0,3,Mr. Ernest Charles Cann,male,21.0,0,0,8.0500
94,0,3,Mr. Charles Joseph Shorney,male,22.0,0,0,8.0500
120,0,3,Mr. Leonard Charles Moore,male,19.0,0,0,8.0500
144,0,2,Mr. Joseph Charles Nicholls,male,19.0,1,1,36.7500
154,0,1,Mr. Charles Duane Williams,male,51.0,0,1,61.3792
186,1,1,Mr. Charles Hallace Romaine,male,45.0,0,0,26.5500
241,0,2,Mr. Reginald Charles Coleridge,male,29.0,0,0,10.5000
271,0,1,Mr. Charles H Natsch,male,37.0,0,1,29.7000
341,0,2,Mr. Charles Frederick Waddington Sedgwick,male,25.0,0,0,13.0000
383,0,2,Mr. Charles Henry Davies,male,18.0,0,0,73.5000
404,0,3,Mr. Carl/Charles Peter Widegren,male,51.0,0,0,7.7500
423,1,2,Mrs. Charles V (Ada Maria Winfield) Clarke,female,28.0,1,0,26.0000
429,1,2,Mrs. Charles Alexander (Alice Adelaide Slow) L...,female,42.0,1,0,26.0000
503,1,2,Mrs. Frederick Charles (Jane Richards) Quick,female,33.0,0,2,26.0000
599,0,1,Mr. Charles H Harrington,male,37.0,0,0,42.4000
623,0,2,Rev. Charles Leonard Kirkland,male,57.0,0,0,12.3500
670,1,2,Mr. Charles Wilhelms,male,31.0,0,0,13.0000
673,0,3,Mr. Frederick Charles Sawyer,male,24.5,0,0,8.0500
680,0,3,Mr. Charles Edward Goodwin,male,14.0,5,2,46.9000
692,0,2,Mr. Charles Henry Chapman,male,52.0,0,0,13.5000
816,1,1,Mrs. Charles Melville (Clara Jennings Gregg) Hays,female,52.0,1,1,93.5000
837,0,2,Mr. Thomas Charles Mudd,male,16.0,0,0,10.5000

In [ ]:
#Select all where Sex=Female and Survived=0
df[(df['Sex']=='Male') & (df['Survived']==1)]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, SibSp, PaCh, Fare]
Index: []

In [ ]:
df[(df['Sex'] == 'Female') & (df['Survived'] == 0)]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, SibSp, PaCh, Fare, male, female]
Index: []

Setting and Resetting Index

In [ ]:
df.set_index('Name',inplace=True)

In [ ]:
df.reset_index(inplace=True)

Quering Dataframes with df.query

In [ ]:
df.query('Age>30')

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Male,Male
6,Mr. Timothy J McCarthy,0,1,male,54.0,0,0,51.8625,Male,Male
11,Miss. Elizabeth Bonnell,1,1,female,58.0,0,0,26.5500,Male,Male
...,...,...,...,...,...,...,...,...,...,...
869,Mr. Victor Vander Cruyssen,0,3,male,47.0,0,0,9.0000,Male,Male
875,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,1,1,female,56.0,0,1,83.1583,Male,Male
877,Mr. Johann Markun,0,3,male,33.0,0,0,7.8958,Male,Male
881,Mrs. William (Margaret Norton) Rice,0,3,female,39.0,0,5,29.1250,Male,Male
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500,Male,Male

In [ ]:
#Combined Conditions
df.query("Age > 70 & Sex == 'male'")

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
95,Mr. George B Goldschmidt,0,1,male,71.0,0,0,34.6542,Male,Male
115,Mr. Patrick Connors,0,3,male,70.5,0,0,7.7500,Male,Male
490,Mr. Ramon Artagaveytia,0,1,male,71.0,0,0,49.5042,Male,Male
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.0,0,0,30.0000,Male,Male
847,Mr. Johan Svensson,0,3,male,74.0,0,0,7.7750,Male,Male

In [ ]:
df.query("Survived==1and Sex == 'female'")

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Male,Male
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male
8,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,1,3,female,27.0,0,2,11.1333,Male,Male
9,Mrs. Nicholas (Adele Achem) Nasser,1,2,female,14.0,1,0,30.0708,Male,Male
...,...,...,...,...,...,...,...,...,...,...
870,Mrs. Samuel (Hannah Wizosky) Abelson,1,2,female,28.0,1,0,24.0000,Male,Male
871,Miss. Adele Kiamie Najib,1,3,female,15.0,0,0,7.2250,Male,Male
875,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,1,1,female,56.0,0,1,83.1583,Male,Male
876,Mrs. William (Imanita Parrish Hall) Shelley,1,2,female,25.0,0,1,26.0000,Male,Male
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000,Male,Male

In [ ]:
df.query('Name == "Mr. Johan Svensson"')

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
847,Mr. Johan Svensson,0,3,male,74.0,0,0,7.775,Male,Male

In [ ]:
df.query("Name=='Miss. Margaret Edith Graham'")

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0,Male,Male

Sorting

In [ ]:
df.sort_values('Age')

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167,Male,Male
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000,Male,Male
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583,Male,Male
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583,Male,Male
77,Master. Alden Gates Caldwell,1,2,male,0.83,0,2,29.0000,Male,Male
...,...,...,...,...,...,...,...,...,...,...
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500,Male,Male
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042,Male,Male
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542,Male,Male
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750,Male,Male
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000,Male,Male

In [ ]:
df.sort_values('Fare')

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
630,Mr. William Henry Marsh Parr,0,1,male,30.0,0,0,0.0000,Male,Male
811,Mr. Richard Fry,0,1,male,39.0,0,0,0.0000,Male,Male
411,Mr. Alfred Fleming Cunningham,0,2,male,22.0,0,0,0.0000,Male,Male
671,Mr. Ennis Hastings Watson,0,2,male,19.0,0,0,0.0000,Male,Male
275,Mr. Francis Parkes,0,2,male,21.0,0,0,0.0000,Male,Male
...,...,...,...,...,...,...,...,...,...,...
435,Mr. Mark Fortune,0,1,male,64.0,1,4,263.0000,Male,Male
87,Miss. Mabel Helen Fortune,1,1,female,23.0,3,2,263.0000,Male,Male
676,Mr. Thomas Drake Martinez Cardeza,1,1,male,36.0,0,1,512.3292,Male,Male
733,Mr. Gustave J Lesurer,1,1,male,35.0,0,0,512.3292,Male,Male
257,Miss. Anna Ward,1,1,female,35.0,0,0,512.3292,Male,Male

In [ ]:
df.sort_values('Age',ascending=False)

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000,Male,Male
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750,Male,Male
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542,Male,Male
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042,Male,Male
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500,Male,Male
...,...,...,...,...,...,...,...,...,...,...
827,Master. George Sibley Richards,1,2,male,0.83,1,1,18.7500,Male,Male
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583,Male,Male
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583,Male,Male
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000,Male,Male
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167,Male,Male

In [ ]:
df.sort_values(['Age','Fare'])

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167,Male,Male
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000,Male,Male
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583,Male,Male
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583,Male,Male
827,Master. George Sibley Richards,1,2,male,0.83,1,1,18.7500,Male,Male
...,...,...,...,...,...,...,...,...,...,...
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500,Male,Male
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542,Male,Male
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042,Male,Male
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750,Male,Male
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000,Male,Male

In [ ]:
df.sort_index()

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Male,Male
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Male,Male
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Male,Male
...,...,...,...,...,...,...,...,...,...,...
882,Rev. Juozas Montvila,0,2,male,27.0,0,0,13.0000,Male,Male
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000,Male,Male
884,Miss. Catherine Helen Johnston,0,3,female,7.0,1,2,23.4500,Male,Male
885,Mr. Karl Howell Behr,1,1,male,26.0,0,0,30.0000,Male,Male
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500,Male,Male

Group By.

In [ ]:
# Group by class
class_group = df.groupby('Pclass')
# This alone is not useful, unless you use operations like .sum, .mean
class_group

In [ ]:
class_group['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.707707
Name: Fare, dtype: float64

In [ ]:
#Grouping by gender
gender_group=df.groupby('Sex')
gender_group['Survived'].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [ ]:
#Grouping by survival
survival_group=df.groupby('Survived')
survival_group['Survived'].sum()

Survived
0      0
1    342
Name: Survived, dtype: int64

In [ ]:
#Total fare per class
class_group['Fare'].sum()

Pclass
1    18177.4125
2     3801.8417
3     6675.6535
Name: Fare, dtype: float64

In [ ]:
#Multiple Aggregration
class_group.agg({"Fare":['mean','min','max']})

             Fare
             mean  min       max
Pclass
1       84.154687  0.0  512.3292
2       20.662183  0.0   73.5000
3       13.707707  0.0   69.5500

In [ ]:
# find the passengers with the max and min fare from each class
class_group.agg({'Fare':['max','min']})

            Fare
             max  min
Pclass
1       512.3292  0.0
2        73.5000  0.0
3        69.5500  0.0

In [ ]:
df[df['Fare']==69.5500]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
158,Master. Thomas Henry Sage,0,3,male,5.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
179,Miss. Constance Gladys Sage,0,3,female,8.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
200,Mr. Frederick Sage,0,3,male,17.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
322,Mr. George John Jr Sage,0,3,male,20.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
788,Miss. Stella Anna Sage,0,3,female,21.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
842,Mr. Douglas Bullen Sage,0,3,male,18.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
859,Miss. Dorothy Edith Sage,0,3,female,14.0,8,2,69.55,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55

### Renaming Columns and Index

In [ ]:
df.rename(columns={'Name':'FullName'},inplace=True)

In [ ]:
df

,FirstName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,Rev. Juozas Montvila,0,2,male,27.0,0,0,13.0000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
884,Miss. Catherine Helen Johnston,0,3,female,7.0,1,2,23.4500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
885,Mr. Karl Howell Behr,1,1,male,26.0,0,0,30.0000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55

In [ ]:
df.rename(index={1:'First',2:'Second'},inplace=True)
df.head()

,FirstName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
First,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
Second,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55

In [ ]:
df.reset_index(inplace=True,drop=True)
df.head()

,FirstName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female,...,6.95,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55

#### Adding Columns and Rows

In [ ]:
#Adding a new column
df['Status']='Poor'

In [ ]:
df.head()

,FirstName,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,male,female,...,8.3,6.4375,39.4,14.1083,13.8583,50.4958,5.0,9.8458,10.5167,Status
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,Rev. Juozas Montvila,0,2,male,27.0,0,0,13.0000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
884,Miss. Catherine Helen Johnston,0,3,female,7.0,1,2,23.4500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
885,Mr. Karl Howell Behr,1,1,male,26.0,0,0,30.0000,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500,Male,Male,...,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,69.55,Poor

In [ ]:
from google.colab import files

In [ ]:
uploaded=files.upload()

Saving titanic.csv to titanic.csv

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('titanic.csv')

In [ ]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [ ]:
df['Status']='Poor'

In [ ]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Poor
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Poor
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [ ]:
#Fill the column based off certain conditions
df.loc[df['Fare']>10,'Status']='Rich'

In [ ]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [ ]:
import numpy as np

In [ ]:
#Inserting at a particular index
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [ ]:
df.insert(1,'ID',101)

In [ ]:
df.head()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,101,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,101,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,101,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,101,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,101,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [ ]:
#Adding a row using loc (if index does not exist)
#Add a new row at index 2
df.loc[2]=[1, 101, 1, 'Tomi Jesu', 'female', 22, 1, 0, 15.0, 'Rich']
df.head()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,101,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,101,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,101,1,Tomi Jesu,female,22.0,1,0,15.0000,Rich
3,1,101,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,101,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [ ]:
#You can also use concat to add a new row at the end
#df = pd.concat([df, new_row], ignore_index=True)

In [ ]:
df.tail()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
882,0,101,2,Rev. Juozas Montvila,male,27.0,0,0,13.00,Rich
883,1,101,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.00,Rich
884,0,101,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45,Rich
885,1,101,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00,Rich
886,0,101,3,Mr. Patrick Dooley,male,32.0,0,0,7.75,Poor

#### Dropping Columns and Rows

In [ ]:
df.drop(columns=['ID'],inplace=True)

In [ ]:
df.drop('Status',axis=1,inplace=True)

In [ ]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [ ]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

How to Save Your DataFrame

In [ ]:
#Take note to always drop the default index. it is always added automatically.
df.to_csv('new_titanic.csv', index=False)

In [ ]:
new_df=pd.read_csv('/content/new_titanic.csv')
new_df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500